import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { CheckCircle2, CircleDashed, ListChecks, TimerReset } from "lucide-react";
import { requireSessionUser } from "@/app/session-auth";
import { findWorkspaceByEmail, getProjectsData, getTasksData, getUnreadNotificationCount } from "@/lib/workspace";
import { AppShell } from "../components/app-shell";
import { TaskForm } from "../components/task-form";
import { TaskStatusActions } from "../components/task-status-actions";
export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Tarefas", description: "Fluxo de execução protegido do Prismivo.", robots: { index: false, follow: false } };
export default async function TasksPage() { const identity = await requireSessionUser("/app/tarefas"); const workspace = await findWorkspaceByEmail(identity.email); if (!workspace) redirect("/app/onboarding"); const [tasks, projects, unreadCount] = await Promise.all([getTasksData(workspace.organizationId), getProjectsData(workspace.organizationId), getUnreadNotificationCount(workspace.userId)]); const todo = tasks.filter((task) => task.status === "todo"); const progress = tasks.filter((task) => task.status === "in_progress"); const done = tasks.filter((task) => task.status === "done"); return <AppShell active="tasks" title="Tarefas" description="Prioridades e andamento da operação" workspace={workspace} unreadCount={unreadCount}><section className="app-page-intro"><div><span className="eyebrow">TRABALHO VISÍVEL</span><h1>Da próxima ação à entrega, sem perder o contexto.</h1><p>Organize prioridades por projeto e mantenha a equipe alinhada com estados simples e rastreáveis.</p></div><TaskForm projects={projects.map(({ id, name, clientName }) => ({ id, name, clientName }))} /></section><section className="app-summary-strip" aria-label="Resumo das tarefas"><article><CircleDashed aria-hidden="true" /><span><strong>{todo.length}</strong><small>a fazer</small></span></article><article><TimerReset aria-hidden="true" /><span><strong>{progress.length}</strong><small>em andamento</small></span></article><article><CheckCircle2 aria-hidden="true" /><span><strong>{done.length}</strong><small>concluídas</small></span></article></section>{tasks.length === 0 ? <section className="dashboard-panel empty-state"><ListChecks aria-hidden="true" /><h2>Nenhuma tarefa ainda</h2><p>Crie a primeira tarefa e ligue-a a um projeto.</p></section> : <section className="task-board" aria-label="Quadro de tarefas"><TaskColumn title="A fazer" items={todo} tone="todo" /><TaskColumn title="Em andamento" items={progress} tone="in_progress" /><TaskColumn title="Concluídas" items={done} tone="done" /></section>}</AppShell>; }
type TaskItem = Awaited<ReturnType<typeof getTasksData>>[number];
function TaskColumn({ title, items, tone }: { title: string; items: TaskItem[]; tone: string }) { return <section className="task-column"><header><span className={`task-column-dot ${tone}`} /><h2>{title}</h2><small>{items.length}</small></header><div>{items.length === 0 ? <p className="column-empty">Nenhuma tarefa nesta etapa.</p> : items.map((task) => <article className={`task-card ${task.status}`} key={task.id}><span className={`priority-badge ${task.priority}`}>{priorityLabel(task.priority)}</span><h3>{task.title}</h3><p>{task.description || "Sem descrição"}</p><div className="task-context"><span>{task.projectName}</span><small>{task.clientName || "Sem cliente"}{task.dueDate ? ` · ${formatShortDate(task.dueDate)}` : ""}</small></div><TaskStatusActions id={task.id} status={task.status} /></article>)}</div></section>; }
function priorityLabel(value: string) { return value === "high" ? "Alta" : value === "low" ? "Baixa" : "Média"; }
function formatShortDate(value: string) { return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short" }).format(new Date(`${value}T12:00:00`)); }
