import type { Metadata } from "next";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ArrowLeft, BriefcaseBusiness, Building2, CalendarDays, Mail } from "lucide-react";
import { requireSessionUser } from "@/app/session-auth";
import { findWorkspaceByEmail, getClientDetail, getUnreadNotificationCount } from "@/lib/workspace";
import { AppShell } from "../../components/app-shell";
export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Detalhes do cliente", description: "Contexto protegido do cliente no Prismivo.", robots: { index: false, follow: false } };
export default async function ClientDetailPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const identity = await requireSessionUser(`/app/clientes/${id}`); const workspace = await findWorkspaceByEmail(identity.email); if (!workspace) redirect("/app/onboarding"); const [detail, unreadCount] = await Promise.all([getClientDetail(workspace.organizationId, id), getUnreadNotificationCount(workspace.userId)]); if (!detail) notFound(); return <AppShell active="clients" title={detail.client.name} description="Cliente e projetos vinculados" workspace={workspace} unreadCount={unreadCount}><Link className="detail-back" href="/app/clientes"><ArrowLeft aria-hidden="true" />Voltar para clientes</Link><section className="detail-hero"><div><span className="eyebrow">RELACIONAMENTO PROTEGIDO</span><h1>{detail.client.name}</h1><p>{detail.client.company || "Cliente independente"}</p></div><span className={`status-badge ${detail.client.status}`}>{detail.client.status === "active" ? "Ativo" : detail.client.status}</span></section><section className="detail-info-grid" aria-label="Informações do cliente"><article><Building2 aria-hidden="true" /><span><small>Empresa</small><strong>{detail.client.company || "Não informada"}</strong></span></article><article><Mail aria-hidden="true" /><span><small>E-mail</small><strong>{detail.client.email || "Não informado"}</strong></span></article><article><CalendarDays aria-hidden="true" /><span><small>Cliente desde</small><strong>{formatDate(detail.client.createdAt)}</strong></span></article><article><BriefcaseBusiness aria-hidden="true" /><span><small>Projetos</small><strong>{detail.projects.length}</strong></span></article></section><section className="dashboard-panel detail-section" aria-labelledby="client-projects-title"><div className="section-mini-heading"><span className="panel-kicker">TRABALHO VINCULADO</span><h2 id="client-projects-title">Projetos do cliente</h2></div>{detail.projects.length === 0 ? <div className="empty-state"><BriefcaseBusiness aria-hidden="true" /><h3>Nenhum projeto vinculado</h3><p>Crie um projeto usando este cliente para formar o histórico.</p></div> : <div className="detail-project-grid">{detail.projects.map((project) => <Link href={`/app/projetos/${project.id}`} key={project.id}><span className={`status-badge ${project.status}`}>{project.status === "completed" ? "Concluído" : "Ativo"}</span><h3>{project.name}</h3><p>{project.description || "Sem descrição"}</p><small>{project.progress}% concluído · {project.dueDate ? `prazo ${formatShortDate(project.dueDate)}` : "sem prazo"}</small></Link>)}</div>}</section></AppShell>; }
function formatDate(value: string) { const date = new Date(value.replace(" ", "T") + "Z"); return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "long", year: "numeric", timeZone: "America/Sao_Paulo" }).format(date); }
function formatShortDate(value: string) { return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${value}T12:00:00`)); }
