import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { Download, Files, HardDrive, ShieldCheck } from "lucide-react";
import { requireSessionUser } from "@/app/session-auth";
import { findWorkspaceByEmail, getFilesData, getProjectsData, getUnreadNotificationCount } from "@/lib/workspace";
import { AppShell } from "../components/app-shell";
import { FileDelete } from "../components/file-delete";
import { FileUpload } from "../components/file-upload";
export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Arquivos", description: "Arquivos privados da empresa no Prismivo.", robots: { index: false, follow: false } };
export default async function FilesPage() { const identity = await requireSessionUser("/app/arquivos"); const workspace = await findWorkspaceByEmail(identity.email); if (!workspace) redirect("/app/onboarding"); const [files, projects, unreadCount] = await Promise.all([getFilesData(workspace.organizationId), getProjectsData(workspace.organizationId), getUnreadNotificationCount(workspace.userId)]); const totalBytes = files.reduce((total, file) => total + file.sizeBytes, 0); const projectFiles = files.filter((file) => file.projectId).length; return <AppShell active="files" title="Arquivos" description="Documentos privados e vinculados" workspace={workspace} unreadCount={unreadCount}><section className="app-page-intro"><div><span className="eyebrow">PRIVADO POR PADRÃO</span><h1>Documentos no projeto certo e fora de URLs públicas.</h1><p>Arquivos são validados, armazenados com chaves opacas e liberados somente após autenticação.</p></div><FileUpload projects={projects.map(({ id, name }) => ({ id, name }))} /></section><section className="app-summary-strip" aria-label="Resumo dos arquivos"><article><Files aria-hidden="true" /><span><strong>{files.length}</strong><small>arquivos ativos</small></span></article><article><HardDrive aria-hidden="true" /><span><strong>{formatBytes(totalBytes)}</strong><small>armazenados</small></span></article><article><ShieldCheck aria-hidden="true" /><span><strong>{projectFiles}</strong><small>ligados a projetos</small></span></article></section><section className="dashboard-panel detail-section" aria-labelledby="file-list-title"><div className="section-mini-heading"><span className="panel-kicker">REPOSITÓRIO DA EMPRESA</span><h2 id="file-list-title">Arquivos disponíveis</h2></div>{files.length === 0 ? <div className="empty-state"><Files aria-hidden="true" /><h3>Nenhum arquivo enviado</h3><p>Envie um documento geral ou vincule-o a um projeto.</p></div> : <div className="file-list">{files.map((file) => <article key={file.id}><span className="file-icon"><Files aria-hidden="true" /></span><div><strong>{file.originalName}</strong><small>{formatBytes(file.sizeBytes)} · {file.uploaderName} · {formatDate(file.createdAt)}</small>{file.projectId ? <Link href={`/app/projetos/${file.projectId}`}>{file.projectName}</Link> : <span>Arquivo geral</span>}</div><a href={`/api/files/${file.id}/download`}><Download aria-hidden="true" />Baixar</a><FileDelete id={file.id} name={file.originalName} /></article>)}</div>}</section></AppShell>; }
function formatBytes(value: number) { if (value === 0) return "0 KB"; return value < 1024 * 1024 ? `${Math.max(1, Math.round(value / 1024))} KB` : `${(value / 1024 / 1024).toFixed(1)} MB`; }
function formatDate(value: string) { const date = new Date(value.replace(" ", "T") + "Z"); return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric", timeZone: "America/Sao_Paulo" }).format(date); }
