import type { SiteLocale } from "./site-locale";

const copy = {
  "pt-BR": {
    team: {
      navTitle: "Equipe", navDescription: "Papéis, convites e acessos", eyebrow: "COLABORAÇÃO SEGURA", title: "As pessoas certas, com o acesso certo.", intro: "Convites expiram, papéis são validados no servidor e a organização nunca fica sem proprietário ativo.",
      protected: "COLABORAÇÃO PROTEGIDA", invite: "Convidar integrante", email: "E-mail profissional", initialRole: "Papel inicial", creating: "Criando…", createInvite: "Criar convite", inviteCreated: "Convite criado. O link abaixo aparece uma única vez.", copied: "Copiado", copyLink: "Copiar link", memberCount: (count: number) => `${count} ATIVOS OU SUSPENSOS`, people: "Pessoas e permissões", you: "você", memberRole: (name: string) => `Papel de ${name}`, memberStatus: (name: string) => `Status de ${name}`, remove: (name: string) => `Remover ${name}`, removeTitle: "Remover acesso", removeConfirm: "Remover este membro da organização?", accessUpdated: "Acesso atualizado com segurança.", accessRemoved: "Acesso removido.", automaticExpiry: "EXPIRAÇÃO AUTOMÁTICA", recentInvites: "Convites recentes", noInvites: "Nenhum convite pendente ou aceito.", expires: (date: string) => `expira em ${date}`, accepted: "aceito", revoke: "Revogar", revoked: "Convite revogado.", invitationError: "Não foi possível criar o convite.", updateError: "Não foi possível atualizar o membro.", removeError: "Não foi possível remover o membro.", revokeError: "Não foi possível revogar o convite.", roles: { owner: "Proprietário", admin: "Administrador", editor: "Editor", support: "Suporte", viewer: "Leitor" }, statuses: { active: "Ativo", suspended: "Suspenso" },
    },
    billing: {
      navTitle: "Planos e assinatura", navDescription: "Cobrança demonstrativa e histórico", eyebrow: "GESTÃO COMERCIAL", title: "Planos claros, preços determinados no servidor.", intro: "Explore o fluxo completo em modo demonstrativo. Nenhuma cobrança real, cartão ou dado financeiro é processado.", currentPlan: "PLANO ATUAL", starter: "Inicial", noSubscription: "Sem assinatura registrada", cycle: (cycle: string, provider: string) => `Ciclo ${cycle} · modo ${provider}.`, annual: "anual", monthly: "mensal", demo: "demonstrativo", integrated: "integrado", freeLimits: "A empresa usa os limites gratuitos até escolher outro plano.", financialSecurity: "SEGURANÇA FINANCEIRA", serverAuthority: "Servidor como autoridade", safetyText: "Preço, plano, organização e permissão são verificados novamente no banco. O navegador não consegue liberar recursos sozinho.", history: "HISTÓRICO", events: "Eventos de cobrança", noEvents: "As mudanças de plano demonstrativas aparecerão aqui.", simulated: "Simulado", demoActivated: "Plano demonstrativo ativado", statuses: { trialing: "Demonstração ativa", active: "Ativo", past_due: "Pagamento pendente", cancelled: "Cancelado" }, plans: "PLANOS", choose: "Escolha o ritmo da operação", periodAria: "Período da assinatura", monthlyButton: "Mensal", annualButton: "Anual · 20% menor", recommended: "Recomendado", perMonth: "/mês", clients: "clientes", projects: "projetos ativos", people: "pessoas na equipe", unlimited: "ilimitados", updating: "Atualizando…", current: "Plano atual", activate: "Ativar demonstração", error: "Não foi possível atualizar o plano.", connectionError: "A conexão falhou. Tente novamente.", success: "Plano demonstrativo atualizado. Nenhuma cobrança foi realizada.", planNames: { free: "Inicial", professional: "Profissional", scale: "Escala" }, planDescriptions: { free: "O essencial para organizar os primeiros clientes.", professional: "Mais capacidade, colaboração e controle para equipes em crescimento.", scale: "Operação ampliada para empresas com maior volume." },
    },
    admin: {
      navTitle: "Administração", navDescription: "Indicadores, relatórios e auditoria", eyebrow: "INTELIGÊNCIA OPERACIONAL", title: "Decisões melhores começam com contexto rastreável.", intro: "Indicadores reais, filtros administrativos e relatórios exportáveis sem romper o isolamento da organização.", metricsAria: "Indicadores administrativos", metrics: ["Membros ativos", "Clientes ativos", "Projetos ativos", "Atendimentos abertos", "Aprovações pendentes"], lastDays: (days: number) => `ÚLTIMOS ${days} DIAS`, activityVolume: "Volume de atividades", actionsRegistered: "ações registradas no período", distribution: (count: number, days: number) => `Distribuição de ${count} atividades nos últimos ${days} dias`, secureReport: "RELATÓRIO SEGURO", ready: "Pronto para análise", reportText: "O arquivo respeita os mesmos filtros desta tela, limita o volume exportado e protege células contra fórmulas maliciosas.", exportCsv: "Exportar CSV", audit: "AUDITORIA OPERACIONAL", organizationActivity: "Atividade da organização", period: "Período", last7: "Últimos 7 dias", last30: "Últimos 30 dias", last90: "Últimos 90 dias", type: "Tipo", allTypes: "Todos os tipos", search: "Buscar na trilha", searchPlaceholder: "Título, detalhe ou recurso", apply: "Aplicar filtros", result: (count: number) => `${count} ${count === 1 ? "registro encontrado" : "registros encontrados"}.`, empty: "Nenhuma atividade corresponde aos filtros.", emptyDetail: "Altere o período ou limpe a busca para ampliar os resultados.", noDetail: "Ação registrada sem detalhe adicional.", paginationAria: "Paginação da auditoria", previous: "Anterior", next: "Próxima", page: (page: number, total: number) => `Página ${page} de ${total}`,
    },
    onboarding: {
      step: "Etapa 1 de 1", eyebrow: "SEU PRIMEIRO ESPAÇO", title: "Vamos preparar a operação da sua empresa.", intro: "Essas informações personalizam o dashboard e criam a separação segura dos seus dados. Você poderá alterá-las depois.", plan: "Plano Inicial · Grátis", planDetail: "Até 3 clientes e 3 projetos ativos, sem cobrança e sem cartão.", cardAria: "Configuração da empresa", operationData: "Dados da operação", time: "Leva menos de dois minutos.", identity: "Identidade confirmada", organization: "Nome da empresa ou operação", organizationPlaceholder: "Ex.: Estúdio Horizonte", slug: "Endereço interno", slugPlaceholder: "sua-empresa", slugHelp: "Se o endereço já existir, criaremos uma variação segura automaticamente.", industry: "Segmento", teamSize: "Tamanho da equipe", industries: { agency: "Agência ou estúdio", consulting: "Consultoria", technology: "Tecnologia", architecture: "Arquitetura", professional: "Serviços profissionais", other: "Outro" }, sizes: { solo: "Somente eu", small: "2 a 5 pessoas", medium: "6 a 15 pessoas", large: "16 a 30 pessoas", enterprise: "31 ou mais" }, terms: "Li e aceito os", termsLink: "Termos de Uso", privacy: "Li a", privacyLink: "Política de Privacidade", privacySuffix: "e compreendo como meus dados serão tratados.", creating: "Criando espaço…", create: "Criar espaço gratuito", security: "O servidor confirma sua identidade e associa os dados somente à sua empresa.", error: "Não foi possível concluir a configuração.", connectionError: "A conexão falhou. Seus dados continuam no formulário; tente novamente.", fieldError: "Revise este campo antes de continuar.", consentError: "É necessário confirmar esta opção para continuar.",
    },
  },
  en: {
    team: {
      navTitle: "Team", navDescription: "Roles, invitations, and access", eyebrow: "SECURE COLLABORATION", title: "The right people, with the right access.", intro: "Invitations expire, roles are validated on the server, and the organization always keeps an active owner.",
      protected: "PROTECTED COLLABORATION", invite: "Invite a team member", email: "Professional email", initialRole: "Initial role", creating: "Creating…", createInvite: "Create invitation", inviteCreated: "Invitation created. The link below is shown only once.", copied: "Copied", copyLink: "Copy link", memberCount: (count: number) => `${count} ACTIVE OR SUSPENDED`, people: "People and permissions", you: "you", memberRole: (name: string) => `${name}'s role`, memberStatus: (name: string) => `${name}'s status`, remove: (name: string) => `Remove ${name}`, removeTitle: "Remove access", removeConfirm: "Remove this member from the organization?", accessUpdated: "Access updated securely.", accessRemoved: "Access removed.", automaticExpiry: "AUTOMATIC EXPIRY", recentInvites: "Recent invitations", noInvites: "No pending or accepted invitations.", expires: (date: string) => `expires ${date}`, accepted: "accepted", revoke: "Revoke", revoked: "Invitation revoked.", invitationError: "We could not create the invitation.", updateError: "We could not update this member.", removeError: "We could not remove this member.", revokeError: "We could not revoke the invitation.", roles: { owner: "Owner", admin: "Administrator", editor: "Editor", support: "Support", viewer: "Viewer" }, statuses: { active: "Active", suspended: "Suspended" },
    },
    billing: {
      navTitle: "Plans and subscription", navDescription: "Demo billing and history", eyebrow: "COMMERCIAL MANAGEMENT", title: "Clear plans, with prices determined on the server.", intro: "Explore the full flow in demo mode. No real charge, card, or financial data is processed.", currentPlan: "CURRENT PLAN", starter: "Starter", noSubscription: "No subscription registered", cycle: (cycle: string, provider: string) => `${cycle} cycle · ${provider} mode.`, annual: "annual", monthly: "monthly", demo: "demo", integrated: "integrated", freeLimits: "The company uses the free limits until it chooses another plan.", financialSecurity: "FINANCIAL SECURITY", serverAuthority: "The server is authoritative", safetyText: "Price, plan, organization, and permission are verified again in the database. The browser cannot unlock features by itself.", history: "HISTORY", events: "Billing events", noEvents: "Demo plan changes will appear here.", simulated: "Simulated", demoActivated: "Demo plan activated", statuses: { trialing: "Demo active", active: "Active", past_due: "Payment pending", cancelled: "Cancelled" }, plans: "PLANS", choose: "Choose the pace of your operation", periodAria: "Subscription period", monthlyButton: "Monthly", annualButton: "Annual · 20% less", recommended: "Recommended", perMonth: "/month", clients: "clients", projects: "active projects", people: "team members", unlimited: "unlimited", updating: "Updating…", current: "Current plan", activate: "Activate demo", error: "We could not update the plan.", connectionError: "The connection failed. Try again.", success: "Demo plan updated. No charge was made.", planNames: { free: "Starter", professional: "Professional", scale: "Scale" }, planDescriptions: { free: "The essentials to organize your first clients.", professional: "More capacity, collaboration, and control for growing teams.", scale: "Expanded operations for higher-volume companies." },
    },
    admin: {
      navTitle: "Administration", navDescription: "Metrics, reports, and audit", eyebrow: "OPERATIONAL INTELLIGENCE", title: "Better decisions start with traceable context.", intro: "Real metrics, administrative filters, and exportable reports without breaking organization isolation.", metricsAria: "Administrative metrics", metrics: ["Active members", "Active clients", "Active projects", "Open support requests", "Pending approvals"], lastDays: (days: number) => `LAST ${days} DAYS`, activityVolume: "Activity volume", actionsRegistered: "actions recorded in the period", distribution: (count: number, days: number) => `Distribution of ${count} activities over the last ${days} days`, secureReport: "SECURE REPORT", ready: "Ready for analysis", reportText: "The file follows the same filters as this screen, limits the exported volume, and protects cells against malicious formulas.", exportCsv: "Export CSV", audit: "OPERATIONAL AUDIT", organizationActivity: "Organization activity", period: "Period", last7: "Last 7 days", last30: "Last 30 days", last90: "Last 90 days", type: "Type", allTypes: "All types", search: "Search the trail", searchPlaceholder: "Title, detail, or resource", apply: "Apply filters", result: (count: number) => `${count} ${count === 1 ? "record found" : "records found"}.`, empty: "No activity matches the filters.", emptyDetail: "Change the period or clear the search to broaden the results.", noDetail: "Action recorded without additional details.", paginationAria: "Audit pagination", previous: "Previous", next: "Next", page: (page: number, total: number) => `Page ${page} of ${total}`,
    },
    onboarding: {
      step: "Step 1 of 1", eyebrow: "YOUR FIRST WORKSPACE", title: "Let's prepare your company's operation.", intro: "This information customizes the dashboard and creates secure data separation. You can change it later.", plan: "Starter plan · Free", planDetail: "Up to 3 clients and 3 active projects, with no charge or card.", cardAria: "Company setup", operationData: "Operation details", time: "Takes less than two minutes.", identity: "Identity confirmed", organization: "Company or operation name", organizationPlaceholder: "E.g. Horizon Studio", slug: "Internal address", slugPlaceholder: "your-company", slugHelp: "If the address already exists, we will create a safe variation automatically.", industry: "Industry", teamSize: "Team size", industries: { agency: "Agency or studio", consulting: "Consulting", technology: "Technology", architecture: "Architecture", professional: "Professional services", other: "Other" }, sizes: { solo: "Only me", small: "2 to 5 people", medium: "6 to 15 people", large: "16 to 30 people", enterprise: "31 or more" }, terms: "I have read and accept the", termsLink: "Terms of Use", privacy: "I have read the", privacyLink: "Privacy Policy", privacySuffix: "and understand how my data will be handled.", creating: "Creating workspace…", create: "Create free workspace", security: "The server confirms your identity and associates data only with your company.", error: "We could not complete the setup.", connectionError: "The connection failed. Your data remains in the form; try again.", fieldError: "Review this field before continuing.", consentError: "You must confirm this option to continue.",
    },
  },
  es: {
    team: {
      navTitle: "Equipo", navDescription: "Roles, invitaciones y accesos", eyebrow: "COLABORACIÓN SEGURA", title: "Las personas correctas, con el acceso correcto.", intro: "Las invitaciones caducan, los roles se validan en el servidor y la organización siempre mantiene un propietario activo.",
      protected: "COLABORACIÓN PROTEGIDA", invite: "Invitar integrante", email: "Correo profesional", initialRole: "Rol inicial", creating: "Creando…", createInvite: "Crear invitación", inviteCreated: "Invitación creada. El enlace siguiente aparece una sola vez.", copied: "Copiado", copyLink: "Copiar enlace", memberCount: (count: number) => `${count} ACTIVOS O SUSPENDIDOS`, people: "Personas y permisos", you: "tú", memberRole: (name: string) => `Rol de ${name}`, memberStatus: (name: string) => `Estado de ${name}`, remove: (name: string) => `Eliminar a ${name}`, removeTitle: "Eliminar acceso", removeConfirm: "¿Eliminar este integrante de la organización?", accessUpdated: "Acceso actualizado de forma segura.", accessRemoved: "Acceso eliminado.", automaticExpiry: "CADUCIDAD AUTOMÁTICA", recentInvites: "Invitaciones recientes", noInvites: "No hay invitaciones pendientes o aceptadas.", expires: (date: string) => `caduca el ${date}`, accepted: "aceptada", revoke: "Revocar", revoked: "Invitación revocada.", invitationError: "No fue posible crear la invitación.", updateError: "No fue posible actualizar al integrante.", removeError: "No fue posible eliminar al integrante.", revokeError: "No fue posible revocar la invitación.", roles: { owner: "Propietario", admin: "Administrador", editor: "Editor", support: "Soporte", viewer: "Lector" }, statuses: { active: "Activo", suspended: "Suspendido" },
    },
    billing: {
      navTitle: "Planes y suscripción", navDescription: "Facturación demostrativa e historial", eyebrow: "GESTIÓN COMERCIAL", title: "Planes claros, precios determinados en el servidor.", intro: "Explora el flujo completo en modo demostrativo. No se procesa ningún cobro real, tarjeta o dato financiero.", currentPlan: "PLAN ACTUAL", starter: "Inicial", noSubscription: "Sin suscripción registrada", cycle: (cycle: string, provider: string) => `Ciclo ${cycle} · modo ${provider}.`, annual: "anual", monthly: "mensual", demo: "demostrativo", integrated: "integrado", freeLimits: "La empresa utiliza los límites gratuitos hasta elegir otro plan.", financialSecurity: "SEGURIDAD FINANCIERA", serverAuthority: "El servidor como autoridad", safetyText: "Precio, plan, organización y permiso se verifican nuevamente en la base de datos. El navegador no puede habilitar recursos por sí solo.", history: "HISTORIAL", events: "Eventos de facturación", noEvents: "Los cambios de plan demostrativos aparecerán aquí.", simulated: "Simulado", demoActivated: "Plan demostrativo activado", statuses: { trialing: "Demostración activa", active: "Activo", past_due: "Pago pendiente", cancelled: "Cancelado" }, plans: "PLANES", choose: "Elige el ritmo de la operación", periodAria: "Período de suscripción", monthlyButton: "Mensual", annualButton: "Anual · 20% menos", recommended: "Recomendado", perMonth: "/mes", clients: "clientes", projects: "proyectos activos", people: "personas en el equipo", unlimited: "ilimitados", updating: "Actualizando…", current: "Plan actual", activate: "Activar demostración", error: "No fue posible actualizar el plan.", connectionError: "La conexión falló. Inténtalo de nuevo.", success: "Plan demostrativo actualizado. No se realizó ningún cobro.", planNames: { free: "Inicial", professional: "Profesional", scale: "Escala" }, planDescriptions: { free: "Lo esencial para organizar los primeros clientes.", professional: "Más capacidad, colaboración y control para equipos en crecimiento.", scale: "Operación ampliada para empresas con mayor volumen." },
    },
    admin: {
      navTitle: "Administración", navDescription: "Indicadores, informes y auditoría", eyebrow: "INTELIGENCIA OPERATIVA", title: "Mejores decisiones comienzan con contexto rastreable.", intro: "Indicadores reales, filtros administrativos e informes exportables sin romper el aislamiento de la organización.", metricsAria: "Indicadores administrativos", metrics: ["Miembros activos", "Clientes activos", "Proyectos activos", "Solicitudes abiertas", "Aprobaciones pendientes"], lastDays: (days: number) => `ÚLTIMOS ${days} DÍAS`, activityVolume: "Volumen de actividades", actionsRegistered: "acciones registradas en el período", distribution: (count: number, days: number) => `Distribución de ${count} actividades en los últimos ${days} días`, secureReport: "INFORME SEGURO", ready: "Listo para análisis", reportText: "El archivo respeta los mismos filtros de esta pantalla, limita el volumen exportado y protege las celdas contra fórmulas maliciosas.", exportCsv: "Exportar CSV", audit: "AUDITORÍA OPERATIVA", organizationActivity: "Actividad de la organización", period: "Período", last7: "Últimos 7 días", last30: "Últimos 30 días", last90: "Últimos 90 días", type: "Tipo", allTypes: "Todos los tipos", search: "Buscar en el historial", searchPlaceholder: "Título, detalle o recurso", apply: "Aplicar filtros", result: (count: number) => `${count} ${count === 1 ? "registro encontrado" : "registros encontrados"}.`, empty: "Ninguna actividad corresponde a los filtros.", emptyDetail: "Cambia el período o limpia la búsqueda para ampliar los resultados.", noDetail: "Acción registrada sin detalle adicional.", paginationAria: "Paginación de auditoría", previous: "Anterior", next: "Siguiente", page: (page: number, total: number) => `Página ${page} de ${total}`,
    },
    onboarding: {
      step: "Paso 1 de 1", eyebrow: "TU PRIMER ESPACIO", title: "Preparemos la operación de tu empresa.", intro: "Esta información personaliza el panel y crea una separación segura de tus datos. Podrás cambiarla después.", plan: "Plan Inicial · Gratis", planDetail: "Hasta 3 clientes y 3 proyectos activos, sin cobro ni tarjeta.", cardAria: "Configuración de la empresa", operationData: "Datos de la operación", time: "Toma menos de dos minutos.", identity: "Identidad confirmada", organization: "Nombre de la empresa u operación", organizationPlaceholder: "Ej.: Estudio Horizonte", slug: "Dirección interna", slugPlaceholder: "tu-empresa", slugHelp: "Si la dirección ya existe, crearemos automáticamente una variante segura.", industry: "Sector", teamSize: "Tamaño del equipo", industries: { agency: "Agencia o estudio", consulting: "Consultoría", technology: "Tecnología", architecture: "Arquitectura", professional: "Servicios profesionales", other: "Otro" }, sizes: { solo: "Solo yo", small: "2 a 5 personas", medium: "6 a 15 personas", large: "16 a 30 personas", enterprise: "31 o más" }, terms: "He leído y acepto los", termsLink: "Términos de Uso", privacy: "He leído la", privacyLink: "Política de Privacidad", privacySuffix: "y comprendo cómo se tratarán mis datos.", creating: "Creando espacio…", create: "Crear espacio gratuito", security: "El servidor confirma tu identidad y asocia los datos solamente con tu empresa.", error: "No fue posible completar la configuración.", connectionError: "La conexión falló. Tus datos siguen en el formulario; inténtalo de nuevo.", fieldError: "Revisa este campo antes de continuar.", consentError: "Debes confirmar esta opción para continuar.",
    },
  },
} as const;

export function getManagementCopy(locale: SiteLocale) {
  return copy[locale];
}
