"use client";
import { CheckCircle2, LoaderCircle, Upload, X } from "lucide-react";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
type ProjectOption = { id: string; name: string };
export function FileUpload({ projects, fixedProjectId }: { projects: ProjectOption[]; fixedProjectId?: string }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState(""); const [success, setSuccess] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (submitting) return; const form = event.currentTarget; const data = new FormData(form); if (fixedProjectId) data.set("projectId", fixedProjectId); setSubmitting(true); setMessage("Enviando e validando o arquivo…"); setSuccess(false); try { const response = await fetch("/api/files", { method: "POST", body: data }); const result = await response.json() as { ok: boolean; error?: { message: string } }; if (!response.ok || !result.ok) { setMessage(result.error?.message ?? "Não foi possível enviar o arquivo."); return; } form.reset(); setSuccess(true); setMessage("Arquivo salvo no armazenamento privado."); router.refresh(); } catch { setMessage("A conexão falhou. Tente novamente."); } finally { setSubmitting(false); } }
  return <div className="quick-project"><button className="app-primary-button" type="button" onClick={() => setOpen(true)}><Upload aria-hidden="true" />Enviar arquivo</button>{open && <div className="app-dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><form className="app-dialog" onSubmit={submit} aria-labelledby="file-upload-title"><div className="project-form-heading"><div><span className="panel-kicker">ARMAZENAMENTO PRIVADO</span><h2 id="file-upload-title">Enviar arquivo</h2></div><button type="button" onClick={() => setOpen(false)} aria-label="Fechar formulário"><X aria-hidden="true" /></button></div>{!fixedProjectId && <div className="form-field"><label htmlFor="file-project">Projeto <span>(opcional)</span></label><select id="file-project" name="projectId" defaultValue=""><option value="">Arquivo geral da empresa</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></div>}<label className="upload-dropzone" htmlFor="private-file"><Upload aria-hidden="true" /><strong>Escolha um arquivo protegido</strong><span>PDF, PNG, JPG, TXT, Markdown ou DOCX · até 5 MB</span><input id="private-file" name="file" type="file" required accept=".pdf,.png,.jpg,.jpeg,.txt,.md,.docx" /></label>{submitting && <div className="upload-progress" role="progressbar" aria-label="Envio em andamento"><span /></div>}{message && <div className={`form-message ${success ? "success" : ""}`} role="status">{success && <CheckCircle2 aria-hidden="true" />}{message}</div>}<div className="dialog-actions"><button className="button button-secondary" type="button" onClick={() => setOpen(false)}>Cancelar</button><button className="app-primary-button" type="submit" disabled={submitting}>{submitting ? <><LoaderCircle className="spin" aria-hidden="true" />Enviando…</> : "Salvar com segurança"}</button></div></form></div>}</div>;
}
