"use client";
import { CheckCircle2, LoaderCircle, Plus, X } from "lucide-react";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type ProjectOption = { id: string; name: string; clientName?: string | null };
export function TaskForm({ projects, fixedProjectId }: { projects: ProjectOption[]; fixedProjectId?: string }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState(""); const [success, setSuccess] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (submitting) return; const form = event.currentTarget; const data = new FormData(form); setSubmitting(true); setMessage(""); setSuccess(false);
    try {
      const response = await fetch("/api/tasks", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ projectId: fixedProjectId ?? data.get("projectId"), title: data.get("title"), description: data.get("description"), priority: data.get("priority"), dueDate: data.get("dueDate") }) });
      const result = await response.json() as { ok: boolean; error?: { message: string } }; if (!response.ok || !result.ok) { setMessage(result.error?.message ?? "Não foi possível criar a tarefa."); return; }
      form.reset(); setSuccess(true); setMessage("Tarefa adicionada ao fluxo."); router.refresh();
    } catch { setMessage("A conexão falhou. Tente novamente."); } finally { setSubmitting(false); }
  }
  return <div className="quick-project"><button className="app-primary-button" type="button" onClick={() => setOpen(true)} disabled={projects.length === 0} title={projects.length === 0 ? "Crie um projeto primeiro" : undefined}><Plus aria-hidden="true" />Nova tarefa</button>{open && <div className="app-dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><form className="app-dialog" onSubmit={submit} aria-labelledby="task-form-title"><div className="project-form-heading"><div><span className="panel-kicker">EXECUÇÃO</span><h2 id="task-form-title">Criar tarefa</h2></div><button type="button" onClick={() => setOpen(false)} aria-label="Fechar formulário"><X aria-hidden="true" /></button></div>{!fixedProjectId && <div className="form-field"><label htmlFor="task-project">Projeto</label><select id="task-project" name="projectId" required defaultValue=""><option value="" disabled>Selecione um projeto</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}{project.clientName ? ` · ${project.clientName}` : ""}</option>)}</select></div>}<div className="form-field"><label htmlFor="task-title">Título</label><input id="task-title" name="title" required minLength={3} maxLength={120} autoFocus /></div><div className="form-field"><label htmlFor="task-description">Descrição <span>(opcional)</span></label><textarea id="task-description" name="description" rows={4} maxLength={700} /></div><div className="form-row"><div className="form-field"><label htmlFor="task-priority">Prioridade</label><select id="task-priority" name="priority" defaultValue="medium"><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option></select></div><div className="form-field"><label htmlFor="task-due-date">Prazo <span>(opcional)</span></label><input id="task-due-date" name="dueDate" type="date" /></div></div>{message && <div className={`form-message ${success ? "success" : ""}`} role="status">{success && <CheckCircle2 aria-hidden="true" />}{message}</div>}<div className="dialog-actions"><button className="button button-secondary" type="button" onClick={() => setOpen(false)}>Cancelar</button><button className="app-primary-button" type="submit" disabled={submitting}>{submitting ? <><LoaderCircle className="spin" aria-hidden="true" />Salvando…</> : "Criar tarefa"}</button></div></form></div>}</div>;
}
