"use client";
import { CheckCircle2, LoaderCircle, Plus, X } from "lucide-react";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { getOperationalCopy } from "@/lib/app-operational-i18n";
import type { SiteLocale } from "@/lib/site-locale";

type ProjectOption = { id: string; name: string; clientName?: string | null };
export function TaskForm({ projects, fixedProjectId, locale = "pt-BR" }: { projects: ProjectOption[]; fixedProjectId?: string; locale?: SiteLocale }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState(""); const [success, setSuccess] = useState(false);
  const copy = getOperationalCopy(locale);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (submitting) return; const form = event.currentTarget; const data = new FormData(form); setSubmitting(true); setMessage(""); setSuccess(false);
    try {
      const response = await fetch("/api/tasks", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ projectId: fixedProjectId ?? data.get("projectId"), title: data.get("title"), description: data.get("description"), priority: data.get("priority"), dueDate: data.get("dueDate") }) });
      const result = await response.json() as { ok: boolean; error?: { message: string } }; if (!response.ok || !result.ok) { setMessage(locale === "pt-BR" && result.error?.message ? result.error.message : copy.tasks.form.createError); return; }
      form.reset(); setSuccess(true); setMessage(copy.tasks.form.success); router.refresh();
    } catch { setMessage(copy.common.connectionError); } finally { setSubmitting(false); }
  }
  return <div className="quick-project"><button className="app-primary-button" type="button" onClick={() => setOpen(true)} disabled={projects.length === 0} title={projects.length === 0 ? copy.tasks.form.firstProject : undefined}><Plus aria-hidden="true" />{copy.tasks.form.newTask}</button>{open && <div className="app-dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><form className="app-dialog" onSubmit={submit} aria-labelledby="task-form-title"><div className="project-form-heading"><div><span className="panel-kicker">{copy.tasks.form.execution}</span><h2 id="task-form-title">{copy.tasks.form.createTask}</h2></div><button type="button" onClick={() => setOpen(false)} aria-label={copy.tasks.form.close}><X aria-hidden="true" /></button></div>{!fixedProjectId && <div className="form-field"><label htmlFor="task-project">{copy.tasks.form.project}</label><select id="task-project" name="projectId" required defaultValue=""><option value="" disabled>{copy.tasks.form.selectProject}</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}{project.clientName ? ` · ${project.clientName}` : ""}</option>)}</select></div>}<div className="form-field"><label htmlFor="task-title">{copy.tasks.form.title}</label><input id="task-title" name="title" required minLength={3} maxLength={120} autoFocus /></div><div className="form-field"><label htmlFor="task-description">{copy.tasks.form.description} <span>({copy.common.optional})</span></label><textarea id="task-description" name="description" rows={4} maxLength={700} /></div><div className="form-row"><div className="form-field"><label htmlFor="task-priority">{copy.tasks.form.priority}</label><select id="task-priority" name="priority" defaultValue="medium"><option value="low">{copy.tasks.priorities.low}</option><option value="medium">{copy.tasks.priorities.medium}</option><option value="high">{copy.tasks.priorities.high}</option></select></div><div className="form-field"><label htmlFor="task-due-date">{copy.tasks.form.deadline} <span>({copy.common.optional})</span></label><input id="task-due-date" name="dueDate" type="date" /></div></div>{message && <div className={`form-message ${success ? "success" : ""}`} role="status">{success && <CheckCircle2 aria-hidden="true" />}{message}</div>}<div className="dialog-actions"><button className="button button-secondary" type="button" onClick={() => setOpen(false)}>{copy.common.cancel}</button><button className="app-primary-button" type="submit" disabled={submitting}>{submitting ? <><LoaderCircle className="spin" aria-hidden="true" />{copy.common.saving}</> : copy.tasks.form.createTask}</button></div></form></div>}</div>;
}
