"use client";
import { CheckCircle2, LoaderCircle, Plus, X } from "lucide-react";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
type ClientOption = { id: string; name: string; company: string | null };
export function TicketForm({ clients }: { clients: ClientOption[] }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState(""); const [success, setSuccess] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (submitting) return; const form = event.currentTarget; const data = new FormData(form); setSubmitting(true); setMessage(""); setSuccess(false); try { const response = await fetch("/api/tickets", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ clientId: data.get("clientId") || undefined, category: data.get("category"), priority: data.get("priority"), subject: data.get("subject"), message: data.get("message") }) }); const result = await response.json() as { ok: boolean; data?: { id: string }; error?: { message: string } }; if (!response.ok || !result.ok) { setMessage(result.error?.message ?? "Não foi possível abrir o atendimento."); return; } form.reset(); setSuccess(true); setMessage("Solicitação aberta com protocolo próprio."); router.refresh(); if (result.data?.id) router.push(`/app/atendimento/${result.data.id}`); } catch { setMessage("A conexão falhou. Tente novamente."); } finally { setSubmitting(false); } }
  return <div className="quick-project"><button className="app-primary-button" type="button" onClick={() => setOpen(true)}><Plus aria-hidden="true" />Novo atendimento</button>{open && <div className="app-dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><form className="app-dialog" onSubmit={submit} aria-labelledby="ticket-form-title"><div className="project-form-heading"><div><span className="panel-kicker">CENTRAL DE ATENDIMENTO</span><h2 id="ticket-form-title">Abrir solicitação</h2></div><button type="button" onClick={() => setOpen(false)} aria-label="Fechar formulário"><X aria-hidden="true" /></button></div><div className="form-field"><label htmlFor="ticket-client">Cliente <span>(opcional)</span></label><select id="ticket-client" name="clientId" defaultValue=""><option value="">Solicitação interna</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}{client.company ? ` · ${client.company}` : ""}</option>)}</select></div><div className="form-row"><div className="form-field"><label htmlFor="ticket-category">Categoria</label><select id="ticket-category" name="category" defaultValue="technical"><option value="technical">Técnico</option><option value="billing">Cobrança</option><option value="access">Acesso</option><option value="question">Dúvida</option><option value="other">Outro</option></select></div><div className="form-field"><label htmlFor="ticket-priority">Prioridade</label><select id="ticket-priority" name="priority" defaultValue="normal"><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option></select></div></div><div className="form-field"><label htmlFor="ticket-subject">Assunto</label><input id="ticket-subject" name="subject" required minLength={4} maxLength={140} /></div><div className="form-field"><label htmlFor="ticket-message">Mensagem</label><textarea id="ticket-message" name="message" required minLength={10} maxLength={3000} rows={5} /></div>{message && <div className={`form-message ${success ? "success" : ""}`} role="status">{success && <CheckCircle2 aria-hidden="true" />}{message}</div>}<div className="dialog-actions"><button className="button button-secondary" type="button" onClick={() => setOpen(false)}>Cancelar</button><button className="app-primary-button" type="submit" disabled={submitting}>{submitting ? <><LoaderCircle className="spin" aria-hidden="true" />Abrindo…</> : "Gerar protocolo"}</button></div></form></div>}</div>;
}
