import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { CheckCircle2, Clock3, Headphones, Siren } from "lucide-react";
import { requireSessionUser } from "@/app/session-auth";
import { findWorkspaceByEmail, getClientsData, getTicketsData, getUnreadNotificationCount } from "@/lib/workspace";
import { AppShell } from "../components/app-shell";
import { TicketForm } from "../components/ticket-form";
export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Atendimento", description: "Solicitações rastreáveis da empresa no Prismivo.", robots: { index: false, follow: false } };
export default async function SupportPage() { const identity = await requireSessionUser("/app/atendimento"); const workspace = await findWorkspaceByEmail(identity.email); if (!workspace) redirect("/app/onboarding"); const [tickets, clients, unreadCount] = await Promise.all([getTicketsData(workspace.organizationId), getClientsData(workspace.organizationId), getUnreadNotificationCount(workspace.userId)]); const open = tickets.filter((ticket) => ticket.status === "open").length; const high = tickets.filter((ticket) => ticket.priority === "high" && ticket.status === "open").length; const closed = tickets.filter((ticket) => ticket.status === "closed").length; return <AppShell active="support" title="Atendimento" description="Solicitações com protocolo e histórico" workspace={workspace} unreadCount={unreadCount}><section className="app-page-intro"><div><span className="eyebrow">CONVERSAS RASTREÁVEIS</span><h1>Cada solicitação com contexto, prioridade e continuidade.</h1><p>Abra atendimentos internos ou vinculados a clientes e mantenha as respostas organizadas.</p></div><TicketForm clients={clients.map(({ id, name, company }) => ({ id, name, company }))} /></section><section className="app-summary-strip" aria-label="Resumo dos atendimentos"><article><Clock3 aria-hidden="true" /><span><strong>{open}</strong><small>abertos</small></span></article><article><Siren aria-hidden="true" /><span><strong>{high}</strong><small>alta prioridade</small></span></article><article><CheckCircle2 aria-hidden="true" /><span><strong>{closed}</strong><small>encerrados</small></span></article></section><section className="ticket-list" aria-labelledby="ticket-list-title"><div className="section-mini-heading"><span className="panel-kicker">FILA DE ATENDIMENTO</span><h2 id="ticket-list-title">Solicitações</h2></div>{tickets.length === 0 ? <div className="dashboard-panel empty-state"><Headphones aria-hidden="true" /><h3>Nenhuma solicitação</h3><p>Abra um atendimento para gerar o primeiro protocolo.</p></div> : tickets.map((ticket) => <Link className="dashboard-panel ticket-card" href={`/app/atendimento/${ticket.id}`} key={ticket.id}><span className="ticket-icon"><Headphones aria-hidden="true" /></span><div><div className="ticket-meta"><span>{ticket.protocol}</span><small>{categoryLabel(ticket.category)} · {ticket.clientName || "Interno"}</small></div><h3>{ticket.subject}</h3><p>Solicitado por {ticket.requesterName} · atualizado em {formatDate(ticket.updatedAt)}</p></div><div className="ticket-state"><span className={`priority-badge ${ticket.priority}`}>{priorityLabel(ticket.priority)}</span><span className={`ticket-status ${ticket.status}`}>{ticket.status === "closed" ? "Encerrado" : "Aberto"}</span></div></Link>)}</section></AppShell>; }
function categoryLabel(value: string) { return ({ technical: "Técnico", billing: "Cobrança", access: "Acesso", question: "Dúvida", other: "Outro" } as Record<string, string>)[value] ?? value; }
function priorityLabel(value: string) { return value === "high" ? "Alta" : value === "low" ? "Baixa" : "Normal"; }
function formatDate(value: string) { const date = new Date(value.replace(" ", "T") + "Z"); return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit", timeZone: "America/Sao_Paulo" }).format(date); }
